name: Breaking Change Check
on: pull_request
jobs:
  breaking-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.57.0"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${GITHUB_REPOSITORY}.git#subdir=proto"
